In [17]:
import numpy as np

In [18]:
np.nan = 'nan'

In [19]:
print(np.nan)

nan


In [20]:
type(np.nan)

str

In [25]:
int(np.nan)

ValueError: invalid literal for int() with base 10: 'nan'

In [26]:
np.nan + 9

TypeError: can only concatenate str (not "int") to str

In [27]:
np.isnan([12, 9, 0.5, np.nan])

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [28]:
np.isnan([12, 9, 0.5, False])

array([False, False, False, False])

In [ ]:
# 1. whether there is missing
# 2. if yes, how many
# 3. where are they

In [ ]:
# whether any element is true
np.any([1, 0, 0, 0])

# 1 = true, 0 = false

True

In [ ]:
np.isnan([12, 9, 0.5, np.nan]).any()
# np.any to find out whether there is missing value in a row

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
np.isnan([12, 9, 0.5, np.nan]).sum()

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
np.argwhere()

In [22]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [23]:
np.argwhere(np.arange(4).reshape(2,2))

array([[0, 1],
       [1, 0],
       [1, 1]], dtype=int64)

In [24]:
np.argwhere(np.isnan([12, 9, 0.5, np.nan]))

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [29]:
# np.oil

np.all([1, 1, 1, 0])

False

In [30]:
np.isnan([12, 9, 0.5, np.nan]).all()
# np.oil: test whether the entire row/column is empty

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
arr = np.arange(30).reshape((5,6))

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
arr + 1000

array([[1000, 1001, 1002, 1003, 1004, 1005],
       [1006, 1007, 1008, 1009, 1010, 1011],
       [1012, 1013, 1014, 1015, 1016, 1017],
       [1018, 1019, 1020, 1021, 1022, 1023],
       [1024, 1025, 1026, 1027, 1028, 1029]])

In [ ]:
arr > 10

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [ ]:
arr[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
arr[1]

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
arr[:,1]

array([ 1,  7, 13, 19, 25])

In [ ]:
arr[:,[1, 3, 5]]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [ ]:
arr[2,:] > 15

array([False, False, False, False,  True,  True])

In [ ]:
arr[4, arr[2,:] > 15]

array([28, 29])

# exercise - moving average

In [ ]:
import numpy as np

In [ ]:
cases = np.genfromtxt('../data_in/hk_covid_stats.csv', delimiter=',', skip_header=1, usecols=2)

In [ ]:
print(cases.shape, cases.size, cases.dtype, cases.ndim)

(956,) 956 float64 1


In [ ]:
csum = np.cumsum(cases)

In [ ]:
csum.shape

(956,)

In [ ]:
csum[3:] = csum[3:] - csum[:-3]

In [ ]:
mave = np.round(csum[2:]/3, 1)


In [ ]:
mave.shape

(954,)

In [ ]:
mave = np.insert(mave, 0, [np.nan, np.nan])

In [ ]:
mave

array([  nan,   nan,   1.7,   2. ,   2. ,   1. ,   0.7,   0.7,   1.3,
         1. ,   1.7,   1. ,   1.3,   2. ,   3. ,   2.7,   1.7,   1.7,
         4.3,   7.7,   7. ,   5. ,   2.3,   2. ,   1.3,   1.3,   2. ,
         2. ,   2.7,   2. ,   2. ,   2. ,   3.7,   5. ,   5.7,   4.3,
         3.3,   1.3,   1.3,   2. ,   1.7,   3. ,   1.7,   2.3,   1. ,
         3. ,   2.7,   4. ,   4. ,   4.7,   4.7,   4.7,   5.3,   7. ,
         7.3,  12. ,  17.7,  31.3,  30.7,  36.3,  31.7,  36.3,  30. ,
        33.7,  37.3,  39.7,  41.7,  43. ,  51.3,  53.3,  53.7,  50.3,
        38.7,  32.7,  27.7,  27.3,  26. ,  19.7,  18. ,  13.3,  10.3,
         6.7,   4. ,   4. ,   2.7,   3. ,   2.3,   2.7,   1.3,   2. ,
         2.7,   3.3,   2. ,   1.3,   0.7,   0.7,   0. ,   0. ,   0. ,
         0.7,   0.7,   0.7,   0.3,   0.3,   0.3,   1.3,   1.3,   1.3,
         1. ,   1. ,   1. ,   1. ,   1.3,   1.7,   0.7,   1.3,   1. ,
         1. ,   0. ,   2.7,   3.3,   3.3,   0.7,   0. ,   0. ,   0.3,
         0.3,   4.7,

# fix the missing

In [31]:
cases2 = np.genfromtxt('../data_in/hk_covid_stats.csv', delimiter=',', skip_header=1, usecols=2)

In [34]:
np.isnan(cases2).sum()

2

In [35]:
np.argwhere(np.isnan(cases2))

array([[589],
       [625]], dtype=int64)

In [37]:
cases2[588:591]

array([ 0., nan,  1.])

In [39]:
cases2[624:627]

array([ 2., nan, 31.])

In [40]:
cases2[589] = (cases2[588] + cases2[590]) / 2
cases2[625] = (cases2[624] + cases2[626]) / 2

In [41]:
cases2[624:627]

array([ 2. , 16.5, 31. ])

In [42]:
np.isnan(cases2).sum()

0

In [43]:
cases3 = np.genfromtxt('../data_in/hk_covid_stats.csv', delimiter=',', skip_header=1, usecols=2)

In [47]:
cases3[np.isnan(cases3)] = 0, 0

In [48]:
np.isnan(cases3).any()

False

In [ ]:
np.genfromtxt?

In [50]:
csum2 = np.cumsum(cases2)
csum2[3:] = csum2[3:] - csum2[:-3]
mave2 = np.round(csum2[2:]/3, 1)
mave2 = np.insert(mave2, 0, [np.nan, np.nan])


In [51]:
cases2.shape, mave2.shape

((956,), (956,))

In [52]:
zip(cases2, mave2)

In [55]:
# option1, using zip
np.array(list(zip(cases2, mave2)), dtype= float)

array([[2.00000e+00,         nan],
       [0.00000e+00,         nan],
       [3.00000e+00, 1.70000e+00],
       ...,
       [9.90100e+03, 9.99400e+03],
       [1.04260e+04, 1.03043e+04],
       [1.06830e+04, 1.03367e+04]])

In [58]:
# option2, using np.hstack

np.hstack((cases2.reshape(956, 1), mave2.reshape(956, 1)))


array([[2.00000e+00,         nan],
       [0.00000e+00,         nan],
       [3.00000e+00, 1.70000e+00],
       ...,
       [9.90100e+03, 9.99400e+03],
       [1.04260e+04, 1.03043e+04],
       [1.06830e+04, 1.03367e+04]])

In [65]:
# option3, using np.vstack

result = np.vstack((cases2,mave2)).T

In [63]:
np.savetxt?

Signature:      
np.savetxt(
    fname,
    X,
    fmt='%.18e',
    delimiter=' ',
    newline='\n',
    header='',
    footer='',
    comments='# ',
    encoding=None,
)
Call signature:  np.savetxt(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function savetxt at 0x000001FBFF467F60>
File:            c:\users\zzzのwlkq\appdata\local\programs\python\python311\lib\site-packages\numpy\lib\npyio.py
Docstring:      
Save an array to a text file.

Parameters
----------
fname : filename or file handle
    If the filename ends in ``.gz``, the file is automatically saved in
    compressed gzip format.  `loadtxt` understands gzipped files
    transparently.
X : 1D or 2D array_like
    Data to be saved to a text file.
fmt : str or sequence of strs, optional
    A single format (%10.5f), a sequence of formats, or a
    multi-format string, e.g. 'Iteration %d -- %10.5f', in which
    case `delimiter` is ignored. For complex `X`, the legal options
    for `fmt` are:

  

In [67]:
np.savetxt('../data_out/moving_ave2.csv', 
           result,
           fmt='%.1f',
           delimiter=',',
           header='new cases, moving ave @ 3',
           encoding='utf-8')